name: Update Last Commit Date
permissions:
  contents: write

on:
  push:
    branches:
      - main  

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get latest commit date with ordinal
        id: commit_date
        run: |
          # Extract day, month, year
          DAY=$(git log -1 --format=%cd --date=format:'%d')
          MONTH=$(git log -1 --format=%cd --date=format:'%b')
          YEAR=$(git log -1 --format=%cd --date=format:'%Y')

          # Remove leading zero from day
          DAY=$(echo $DAY | sed 's/^0//')

          # Determine ordinal suffix
          if [ $DAY -eq 1 ] || [ $DAY -eq 21 ] || [ $DAY -eq 31 ]; then
            SUFFIX="st"
          elif [ $DAY -eq 2 ] || [ $DAY -eq 22 ]; then
            SUFFIX="nd"
          elif [ $DAY -eq 3 ] || [ $DAY -eq 23 ]; then
            SUFFIX="rd"
          else
            SUFFIX="th"
          fi

          # Construct formatted date
          FORMATTED_DATE="$MONTH $DAY$SUFFIX, $YEAR"
          echo "LAST_COMMIT_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
          echo "Latest commit date: $FORMATTED_DATE"

      - name: Replace only the date
        run: |
          sed -i "s/\(Updated \)[A-Za-z0-9, ]*/\1$LAST_COMMIT_DATE /" index.html

      - name: Commit updated index.html
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git diff --cached --quiet || git commit -m "Update last commit date"
          git push
