name: Update Last Commit Date
permissions:
  contents: write
on:
  push:
    branches:
      - main  

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get latest commit date
        id: commit_date
        run: |
          echo "LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%b %d, %Y')" >> $GITHUB_ENV

      - name: Replace only the date
        run: |
          # This keeps all text, only swaps out the date after "Updated"
          sed -i "s/\(Updated \)[A-Za-z0-9, ]*/\1$LAST_COMMIT_DATE/" index.html

      - name: Commit updated index.html
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git diff --cached --quiet || git commit -m "Update last commit date"
          git push